(()=>{
  if(document.querySelector('.jp-journey')) return;
  const stops=[
    {x:900,num:'01',title:'Player first',lead:'I begin with the player journey: what they need to notice, decide and feel before visual polish begins.',tone:'coral',chips:['Flows','Hierarchy','Accessibility'],link:'#process',cards:[['PLAYER PATH','GOAL → CHOICE → FEEDBACK'],['UI SYSTEM','HUD · MENUS · STATES']]},
    {x:1780,num:'02',title:'Game worlds',lead:'Diegetic interfaces, HUDs and menus designed to strengthen the fiction while keeping every action readable.',tone:'dark',chips:['The Dark Arrival','Suite 13','Astra'],link:'#work',cards:[['SHIPPED ON STEAM','THE DARK ARRIVAL'],['REAL-TIME UI','UE5 · UMG · BLUEPRINTS']]},
    {x:2660,num:'03',title:'Spatial clues',lead:'Fieldnotes turns an investigator journal into an executable Unity experience with 3D clues, evidence links and a case timeline.',tone:'blue',chips:['Fieldnotes','Unity 6','Spatial UI'],link:'#fieldnotes-feature',cards:[['EVIDENCE 03/03','KEY · RECORDER · LETTER'],['INTERACTION','ROTATE · ZOOM · CONNECT']]},
    {x:3540,num:'04',title:'Systems that ship',lead:'I translate Figma systems into reusable engine components, responsive states and production-ready behavior.',tone:'lime',chips:['Figma','Unity C#','UE5 UMG'],link:'#capabilities',cards:[['PIPELINE','DESIGN → BUILD → TEST'],['PRODUCTION','GIT · PERFORCE · JIRA']]},
    {x:4420,num:'05',title:'Work in motion',lead:'Motion explains hierarchy, confirms input and gives interfaces the pacing their game or product needs.',tone:'coral',chips:['Motion','Feedback','Prototypes'],link:'#showcase',cards:[['STATE CHANGE','IDLE → FOCUS → CONFIRM'],['TOOLS','AFTER EFFECTS · ENGINE']]},
    {x:5300,num:'06',title:'Open to build',lead:'Technical UI/UX Designer in the San Francisco Bay Area, open to game UI, real-time product and spatial-interface opportunities.',tone:'blue',chips:['3+ years','Steam + Google Play','SF Bay Area'],link:'#contact',cards:[['CURRENT STATUS','AVAILABLE FOR OPPORTUNITIES'],['CONTACT','JAIKARDEVGAME@GMAIL.COM']]}
  ];
  const launch=document.createElement('button'); launch.className='jp-journey-launch'; launch.type='button'; launch.innerHTML='Play my journey <span aria-hidden="true">→</span>'; document.body.appendChild(launch);
  const root=document.createElement('section'); root.className='jp-journey'; root.setAttribute('aria-label','Interactive portfolio journey'); root.setAttribute('aria-hidden','true');
  root.innerHTML=`<div class="jp-journey__grain"></div><header class="jp-journey__top"><div class="jp-journey__brand">JAIKAR.STUDIO <span>/ INTERACTIVE JOURNEY</span></div><div class="jp-journey__actions"><button class="jp-journey__btn" data-map>Journey map</button><button class="jp-journey__btn" data-close>Exit to portfolio ×</button></div></header><div class="jp-journey__viewport"><div class="jp-journey__world"><div class="jp-journey__sky"></div><div class="jp-journey__orb" style="left:40px"></div><div class="jp-journey__orb" style="left:2450px;top:-350px"></div><div class="jp-journey__orb" style="left:5050px"></div><div class="jp-journey__path"></div><div class="jp-journey__intro"><div class="jp-journey__eyebrow">Act I / The playable portfolio</div><h2>Walk<br>the work.</h2><p>Move through the decisions, tools and shipped interfaces behind my practice. Every checkpoint opens the full evidence in the portfolio.</p><div class="jp-journey__hint"><span><b class="jp-key">A</b> back</span><span><b class="jp-key">D</b> forward</span><span>or scroll / swipe</span></div></div>${stops.map((s,i)=>`<article class="jp-stop" data-stop="${i}" data-tone="${s.tone}" style="left:${s.x}px"><div class="jp-stop__num">${s.num} / JOURNEY CHECKPOINT</div><h3>${s.title}</h3><p class="jp-stop__lead">${s.lead}</p><div class="jp-stop__scene">${s.cards.map((c,j)=>`<div class="jp-ui-card" style="left:${28+j*210}px;top:${30+j*58}px;width:190px"><b>${c[0]}</b><span>${c[1]}</span><i></i><i></i></div>`).join('')}<div class="jp-stop__chips">${s.chips.map(c=>`<span class="jp-stop__chip">${c}</span>`).join('')}</div><a class="jp-stop__link" href="${s.link}" aria-label="Open ${s.title} in the portfolio">↗</a></div></article>`).join('')}<div class="jp-avatar" aria-hidden="true"><div class="jp-avatar__head"></div><div class="jp-avatar__body"></div><i class="jp-avatar__leg a"></i><i class="jp-avatar__leg b"></i></div></div><div class="jp-journey__hud"><div class="jp-journey__progress"><div class="jp-journey__progress-label"><span>YOUR WALK</span><span data-place>ENTRANCE</span></div><div class="jp-journey__rail"><div class="jp-journey__fill"></div></div></div><div class="jp-journey__count"><span data-count>00</span><small>/ 06 MEMORIES</small></div></div><div class="jp-journey__toast" role="status">Use A / D, arrow keys, scroll or swipe</div></div>`;
  document.body.appendChild(root);
  const worldNode=root.querySelector('.jp-journey__world');
  worldNode.insertAdjacentHTML('afterbegin',`<div class="jp-scenery"><i class="jp-cloud" style="left:720px;top:18%"></i><i class="jp-cloud" style="left:2280px;top:24%;transform:scale(.72)"></i><i class="jp-cloud" style="left:4700px;top:16%;transform:scale(1.18)"></i><i class="jp-hill" style="left:1280px"></i><i class="jp-hill" style="left:3220px;width:650px"></i><i class="jp-hill" style="left:5100px"></i>${stops.map(s=>`<i class="jp-marker" style="left:${s.x+310}px"></i>`).join('')}</div>`);
  root.insertAdjacentHTML('beforeend',`<aside class="jp-journey__map" aria-label="Journey map"><div class="jp-journey__map-label">ACT II / JOURNEY MAP</div><h3>Choose a memory.</h3><div class="jp-map-grid">${stops.map((s,i)=>`<button class="jp-map-stop" data-jump="${i}"><b>${s.num}</b><span>${s.title}</span></button>`).join('')}</div></aside>`);
  const world=root.querySelector('.jp-journey__world'), avatar=root.querySelector('.jp-avatar'), fill=root.querySelector('.jp-journey__fill'), count=root.querySelector('[data-count]'), place=root.querySelector('[data-place]'), toast=root.querySelector('.jp-journey__toast');
  let pos=0,target=0,touchX=0; const max=5400;
  function render(){pos+=(target-pos)*.14;if(Math.abs(target-pos)<.4)pos=target;world.style.transform=`translate3d(${-pos}px,0,0)`;avatar.classList.toggle('is-walking',Math.abs(target-pos)>2);const idx=stops.reduce((n,s,i)=>pos>s.x-500?i+1:n,0);fill.style.width=`${Math.min(100,pos/max*100)}%`;count.textContent=String(idx).padStart(2,'0');place.textContent=idx?stops[idx-1].title.toUpperCase():'ENTRANCE';if(pos!==target)requestAnimationFrame(render)}
  function move(delta){target=Math.max(0,Math.min(max,target+delta));requestAnimationFrame(render)}
  function open(){root.classList.add('is-open');root.setAttribute('aria-hidden','false');document.documentElement.style.overflow='hidden';target=0;pos=0;render();setTimeout(()=>toast.classList.add('show'),350);setTimeout(()=>toast.classList.remove('show'),2600);root.querySelector('[data-close]').focus()}
  function close(){root.classList.remove('is-open');root.setAttribute('aria-hidden','true');document.documentElement.style.overflow='';launch.focus()}
  launch.addEventListener('click',open);root.querySelector('[data-close]').addEventListener('click',close);root.querySelector('[data-map]').addEventListener('click',()=>root.classList.toggle('map-open'));
  root.querySelectorAll('[data-jump]').forEach(btn=>btn.addEventListener('click',()=>{const i=Number(btn.dataset.jump);target=Math.max(0,stops[i].x-window.innerWidth*.27);root.classList.remove('map-open');requestAnimationFrame(render)}));
  root.addEventListener('click',e=>{const a=e.target.closest('.jp-stop__link');if(a){e.preventDefault();const href=a.getAttribute('href');close();setTimeout(()=>document.querySelector(href)?.scrollIntoView({behavior:'smooth'}),80)}});
  root.addEventListener('wheel',e=>{e.preventDefault();move((Math.abs(e.deltaX)>Math.abs(e.deltaY)?e.deltaX:e.deltaY)*1.35)},{passive:false});
  root.addEventListener('touchstart',e=>touchX=e.touches[0].clientX,{passive:true});root.addEventListener('touchmove',e=>{const x=e.touches[0].clientX;move((touchX-x)*1.6);touchX=x},{passive:true});
  window.addEventListener('keydown',e=>{if(!root.classList.contains('is-open'))return;e.preventDefault();e.stopImmediatePropagation();if(['d','D','ArrowRight'].includes(e.key))move(720);if(['a','A','ArrowLeft'].includes(e.key))move(-720);if(e.key==='Escape'){if(root.classList.contains('map-open'))root.classList.remove('map-open');else close()}},true);
  root.addEventListener('pointermove',e=>{const x=(e.clientX/window.innerWidth-.5)*8;root.querySelectorAll('.jp-cloud').forEach((c,i)=>c.style.marginLeft=`${x*(i+1)*.4}px`)});
})();
