(()=>{
if(document.querySelector('.motion-doodles'))return;
const root=document.documentElement,reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
root.classList.add('motion-ready');
if('xr'in navigator)root.classList.add('xr-capable');
const studioCursor=document.createElement('div');studioCursor.className='studio-cursor is-visible';studioCursor.innerHTML='<i></i><b>SELECT</b>';document.body.appendChild(studioCursor);
addEventListener('pointermove',e=>{studioCursor.style.setProperty('--cursor-x',`${e.clientX}px`);studioCursor.style.setProperty('--cursor-y',`${e.clientY}px`);studioCursor.classList.add('is-visible');studioCursor.classList.toggle('is-action',!!e.target.closest('button,a'))},{passive:true});
addEventListener('pointerleave',()=>studioCursor.classList.remove('is-visible'));
const replaceNavPortrait=()=>{const img=document.querySelector('header img[alt*="Jaikar UI Studio"]');if(img)img.src='/Assets/static-ui/jaikar-nav-portrait.png?v=2'};replaceNavPortrait();setTimeout(replaceNavPortrait,600);setTimeout(replaceNavPortrait,1800);
const intro=document.createElement('section');intro.className='studio-intro';intro.setAttribute('aria-label','Jaikar Studio interactive introduction');intro.innerHTML=`
<div class="studio-stars" aria-hidden="true"></div>
<div class="studio-intro__hud"><span>JAIKAR STUDIO</span><span>PORTFOLIO JOURNEY / 2026</span></div>
<div class="studio-screen studio-screen--welcome is-active" data-scene="0">
  <div class="studio-copy"><p>PLAYER 01 / PIXEL JOURNEY READY</p><h1>ENTER<br>JAIKAR<br>STUDIO.</h1><p class="studio-lede">Explore a 2.5D pixel district built around my projects, tools and journey as a Technical UI/UX Designer.</p><div class="studio-quick-proof" aria-label="Recruiter quick facts"><span><b>ROLE</b>TECHNICAL UI/UX</span><span><b>SHIPPED</b>STEAM + GOOGLE PLAY</span><span><b>BUILD</b>UNITY C# + UE5 UMG</span><span><b>STATUS</b>OPEN TO WORK</span></div><div class="studio-actions"><button data-intro="start">▶ PLAY MY JOURNEY <em>SPACE</em></button><button data-intro="assistant">● ASK JP-01</button><button data-intro="recruiter">↓ RECRUITER · 60 SEC</button></div></div>
  <div class="studio-avatar"><span class="studio-avatar__halo"></span><img src="/Assets/static-ui/jaikar-nav-portrait.png?v=2" alt="Illustrated portrait of Jaikar Pothula"><b>JAIKAR<br>TECHNICAL UI/UX DESIGNER</b></div>
</div>
<div class="studio-screen studio-screen--journey" data-scene="1">
  <div class="studio-room"><canvas id="studio-game" width="960" height="540" aria-label="Playable Jaikar Studio. Use arrow keys or WASD to move and Space to interact."></canvas><div class="studio-game-hud"><b id="studio-objective">VISIT 0 / 4</b><span>WASD / ARROWS MOVE · SPACE INTERACT</span></div><div class="studio-space-prompt"><b>SPACE</b><span>DISCOVER THE WORK</span></div><div class="studio-touch"><button data-move="up">↑</button><button data-move="left">←</button><button data-move="down">↓</button><button data-move="right">→</button><button data-interact="1">ACT</button></div></div>
  <div class="studio-dialog"><small id="studio-stop">WELCOME / JAIKAR STUDIO</small><h2 id="studio-scene-title">EXPLORE THE STUDIO.</h2><p id="studio-scene-copy">Walk to a glowing station and press Space to inspect the work.</p><div class="studio-tags" id="studio-scene-tags"><span>4 STATIONS</span><span>REAL PROJECTS</span><span>PLAYABLE</span></div><div class="studio-actions"><button data-intro="interact">INTERACT / SPACE</button><button data-intro="skip">EXIT TO PORTFOLIO ↓</button></div></div>
</div>
<div class="studio-intro__progress" aria-hidden="true"><span></span><b>01 / 04</b></div>`;document.body.appendChild(intro);document.body.classList.add('studio-locked');
const journey=[
 ['I BUILD INTERFACES THAT MOVE.','From player flows and visual systems to working Unity and Unreal interfaces.',['FIGMA','UNITY C#','UE5 UMG']],
 ['FIELDNOTES BECOMES SPATIAL.','A Unity 3D investigator journal for inspecting evidence, saving connections and reconstructing a case.',['UNITY 6.3','WORLD-SPACE UI','SPATIAL UX']],
 ['SYSTEMS SHIP IN-ENGINE.','Reusable UMG and Blueprint architecture supports menus, HUDs and diegetic interfaces in production.',['THE DARK ARRIVAL','ASTRA','BLUEPRINTS']],
 ['THE FULL CASE FILE IS BELOW.','Continue into every project, process detail, playable experiment, résumé and contact path.',['SHIPPED WORK','JP-01','AVAILABLE']]
];let journeyStep=0;
const canvas=intro.querySelector('#studio-game'),ctx=canvas.getContext('2d'),keys=new Set(),visited=new Set(),worldArt=new Image();
worldArt.src='/Assets/static-ui/jaikar-studio-pixel-world.png';
const player={x:72,y:414,w:30,h:48,speed:178,dir:1,walk:0,moving:false};
const stations=[
 {x:93,y:330,w:125,h:112,label:'DESIGN LAB',scene:0,doorX:164},
 {x:332,y:328,w:130,h:112,label:'UNITY LAB',scene:1,doorX:406},
 {x:591,y:330,w:130,h:112,label:'UNREAL LAB',scene:2,doorX:651},
 {x:786,y:312,w:136,h:142,label:'PORTFOLIO',scene:3,doorX:850}
];
const snow=Array.from({length:72},(_,i)=>({x:(i*137)%960,y:(i*73)%540,s:1+(i%3),v:9+(i%5)*3}));
let gameOn=false,last=0,near=null,dialogOpen=false,flash=0;
const px=(x,y,w,h,c)=>{ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))};
const drawPlayer=()=>{const bob=player.moving?Math.sin(player.walk*1.8)*2:Math.sin(performance.now()/450)*.7,x=Math.round(player.x),y=Math.round(player.y+bob),flip=player.dir<0?-1:1;ctx.save();ctx.translate(x,y);ctx.scale(flip,1);ctx.imageSmoothingEnabled=false;ctx.fillStyle='rgba(1,5,22,.38)';ctx.beginPath();ctx.ellipse(0,24,18,6,0,0,Math.PI*2);ctx.fill();px(-12,-23,24,21,'#1a101b');px(-15,-17,4,13,'#1a101b');px(11,-17,4,13,'#1a101b');px(-10,-15,20,17,'#d88a6e');px(-7,-11,4,3,'#f6e8df');px(3,-11,4,3,'#f6e8df');px(-13,-25,22,7,'#241724');px(-15,-21,8,9,'#241724');px(-12,2,24,24,'#5578e8');px(-8,5,16,16,'#eee9d8');px(-16,5,5,17,'#d88a6e');px(11,5,5,17,'#d88a6e');const step=player.moving?Math.sin(player.walk*2.5)*5:0;px(-10,25,7,10+step,'#171d47');px(3,25,7,10-step,'#171d47');px(-12,33+step,10,4,'#ece7d7');px(2,33-step,10,4,'#ece7d7');ctx.restore()};
const drawNPC=(x,y,color,name)=>{ctx.save();ctx.translate(x,y);ctx.fillStyle='rgba(0,0,0,.3)';ctx.beginPath();ctx.ellipse(0,22,14,5,0,0,Math.PI*2);ctx.fill();px(-10,-17,20,17,'#35243b');px(-8,-12,16,12,'#e1a07e');px(-10,0,20,22,color);px(-8,21,6,8,'#171d47');px(2,21,6,8,'#171d47');ctx.fillStyle='#f6f2e8';ctx.font='700 8px JetBrains Mono';ctx.textAlign='center';ctx.fillText(name,0,-25);ctx.restore()};
const paint=()=>{const w=canvas.width,h=canvas.height;ctx.imageSmoothingEnabled=false;ctx.fillStyle='#08153f';ctx.fillRect(0,0,w,h);if(worldArt.complete&&worldArt.naturalWidth)ctx.drawImage(worldArt,0,0,w,h);ctx.fillStyle='rgba(4,10,34,.16)';ctx.fillRect(0,0,w,h);const glow=ctx.createLinearGradient(0,360,0,500);glow.addColorStop(0,'rgba(123,151,255,0)');glow.addColorStop(1,'rgba(48,77,164,.28)');ctx.fillStyle=glow;ctx.fillRect(0,330,w,170);stations.forEach((s,i)=>{if(visited.has(i)){ctx.strokeStyle='rgba(255,210,116,.95)';ctx.lineWidth=2;ctx.strokeRect(s.x,s.y,s.w,s.h);ctx.fillStyle='#ffd77a';ctx.font='700 9px JetBrains Mono';ctx.textAlign='center';ctx.fillText('✓ DISCOVERED',s.x+s.w/2,s.y-8)}});drawNPC(255,405,'#e98564','MAYA / UX');drawNPC(525,408,'#9477df','ORBIT / DEV');snow.forEach(p=>{p.y+=p.v/60;if(p.y>520){p.y=0;p.x=(p.x+173)%960}ctx.fillStyle=`rgba(238,242,255,${.35+p.s*.12})`;ctx.fillRect(p.x,p.y,p.s,p.s)});drawPlayer();if(near!==null&&!dialogOpen){const s=stations[near],cx=Math.max(76,Math.min(884,s.doorX));ctx.fillStyle='rgba(4,10,34,.9)';ctx.strokeStyle='#f8d47a';ctx.lineWidth=2;ctx.fillRect(cx-68,278,136,34);ctx.strokeRect(cx-68,278,136,34);ctx.fillStyle='#fff8df';ctx.font='700 10px JetBrains Mono';ctx.textAlign='center';ctx.fillText('SPACE  ·  '+s.label,cx,299)}if(flash>0){ctx.fillStyle=`rgba(255,224,151,${flash})`;ctx.fillRect(0,0,w,h);flash*=.88}};
const setStory=i=>{journeyStep=i;const [title,copy,tags]=journey[i];intro.querySelector('#studio-stop').textContent=`DISCOVERY ${String(i+1).padStart(2,'0')} / ${stations[i].label}`;intro.querySelector('#studio-scene-title').textContent=title;intro.querySelector('#studio-scene-copy').textContent=copy;intro.querySelector('#studio-scene-tags').innerHTML=tags.map(tag=>`<span>${tag}</span>`).join('')};
const interact=()=>{if(near===null)return;const i=near;if(i===3&&visited.size<3){dialogOpen=true;intro.querySelector('#studio-stop').textContent='PORTAL LOCKED / COMPLETE THE JOURNEY';intro.querySelector('#studio-scene-title').textContent='THREE STORIES REMAIN.';intro.querySelector('#studio-scene-copy').textContent='Visit Design, Unity and Unreal first. The portfolio portal opens when the full path is understood.';intro.querySelector('#studio-scene-tags').innerHTML='<span>KEEP EXPLORING</span><span>'+visited.size+' / 3 FOUND</span>';setTimeout(()=>dialogOpen=false,900);return}visited.add(i);setStory(i);flash=.2;dialogOpen=true;intro.querySelector('#studio-objective').textContent=i===3?'PORTAL READY':`DISCOVERED ${Math.min(visited.size,3)} / 3`;intro.querySelector('.studio-intro__progress b').textContent=`${String(Math.min(visited.size,4)).padStart(2,'0')} / 04`;intro.querySelector('.studio-intro__progress span').style.width=`${Math.max(12.5,Math.min(4,visited.size)*25)}%`;if(i===3)setTimeout(closeIntro,1350);else setTimeout(()=>dialogOpen=false,650)};
const loop=t=>{if(!gameOn)return;const dt=Math.min(.034,(t-last)/1000||0);last=t;let dx=0,dy=0;if(!dialogOpen){if(keys.has('arrowleft')||keys.has('a'))dx--;if(keys.has('arrowright')||keys.has('d'))dx++;if(keys.has('arrowup')||keys.has('w'))dy--;if(keys.has('arrowdown')||keys.has('s'))dy++}if(dx&&dy){dx*=.707;dy*=.707}player.moving=!!(dx||dy);if(dx)player.dir=Math.sign(dx);if(player.moving)player.walk+=dt*7;player.x=Math.max(24,Math.min(936,player.x+dx*player.speed*dt));player.y=Math.max(380,Math.min(463,player.y+dy*player.speed*.62*dt));near=null;stations.forEach((s,i)=>{if(Math.abs(player.x-s.doorX)<55&&player.y<438)near=i});paint();requestAnimationFrame(loop)};
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowleft','arrowright','arrowup','arrowdown','w','a','s','d'].includes(k)){keys.add(k);if(gameOn)e.preventDefault()}if((e.key===' '||e.key==='Enter')&&gameOn){e.preventDefault();interact()}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));intro.querySelectorAll('[data-move]').forEach(btn=>{const k={up:'arrowup',down:'arrowdown',left:'arrowleft',right:'arrowright'}[btn.dataset.move];btn.addEventListener('pointerdown',()=>keys.add(k));['pointerup','pointerleave','pointercancel'].forEach(ev=>btn.addEventListener(ev,()=>keys.delete(k)))});intro.querySelector('[data-interact]').addEventListener('click',interact);worldArt.onload=paint;paint();
const closeIntro=()=>{intro.classList.add('is-leaving');document.body.classList.remove('studio-locked');setTimeout(()=>{intro.remove();document.querySelector('#top')?.scrollIntoView({behavior:reduce?'auto':'smooth'})},700)};
intro.addEventListener('click',e=>{const action=e.target.closest('[data-intro]')?.dataset.intro;if(!action)return;if(action==='skip')return closeIntro();if(action==='recruiter'){closeIntro();setTimeout(()=>dock.querySelector('[data-action="recruiter"]')?.click(),760);return}if(action==='assistant'){closeIntro();setTimeout(()=>document.querySelector('#jp01-launch')?.click(),760);return}if(action==='start'){intro.querySelector('[data-scene="0"]').classList.remove('is-active');intro.querySelector('[data-scene="1"]').classList.add('is-active');gameOn=true;last=performance.now();requestAnimationFrame(loop);return}if(action==='interact')interact()});
addEventListener('keydown',e=>{if(!document.body.classList.contains('studio-locked'))return;if(e.key==='Escape')closeIntro();if((e.key==='Enter'||e.key===' ')&&intro.querySelector('[data-scene="0"].is-active'))intro.querySelector('[data-intro="start"]').click()});
if(new URLSearchParams(location.search).get('return')==='park')closeIntro();
const doodles=document.createElement('div');doodles.className='motion-doodles';doodles.setAttribute('aria-hidden','true');doodles.innerHTML=`
<svg class="motion-doodle doodle-path" viewBox="0 0 420 160"><path d="M8 112C72 4 123 151 193 58S300 143 411 24"/><circle cx="8" cy="112" r="5"/><circle cx="411" cy="24" r="5"/></svg>
<svg class="motion-doodle doodle-cube" viewBox="0 0 160 160"><path d="m28 55 52-28 53 28-53 31zM28 55v57l52 30 53-31V55M80 86v56"/><path class="dash" d="m48 44 53 29v57"/></svg>
<svg class="motion-doodle doodle-pad" viewBox="0 0 220 150"><path d="M58 42c-21 5-35 45-38 68-2 17 13 25 25 13l25-24h80l25 24c12 12 27 4 25-13-3-23-17-63-38-68-21-5-30 8-52 8s-31-13-52-8Z"/><path d="M57 65v28M43 79h28"/><circle cx="159" cy="71" r="6"/><circle cx="177" cy="88" r="6"/></svg>
<svg class="motion-doodle doodle-window" viewBox="0 0 210 170"><rect x="18" y="20" width="174" height="128" rx="8"/><path d="M18 52h174M48 37h54M38 75h62v48H38zM118 75h53M118 92h53M118 109h35"/><path class="fill" d="m73 86 15 13-15 13z"/></svg>
<svg class="motion-doodle doodle-orbit" viewBox="0 0 220 170"><ellipse cx="110" cy="85" rx="92" ry="36"/><ellipse cx="110" cy="85" rx="92" ry="36" transform="rotate(58 110 85)"/><circle cx="110" cy="85" r="15"/><circle class="fill" cx="198" cy="79" r="6"/></svg>
<svg class="motion-doodle doodle-cursor" viewBox="0 0 150 180"><path d="M29 18v108l25-24 18 47 20-9-19-46 35-2z"/><path class="dash" d="M19 150c28 18 67 20 108 2"/><path d="m104 27 13-15m-1 37 22-2m-34 26 14 14"/></svg>
<svg class="motion-doodle doodle-flow" viewBox="0 0 250 170"><rect x="14" y="54" width="56" height="38" rx="6"/><rect x="99" y="18" width="58" height="38" rx="6"/><rect x="180" y="92" width="56" height="38" rx="6"/><path d="M70 73h17c9 0 12-9 12-18M157 37h14c12 0 13 15 13 27v28M70 82h42c16 0 18 28 18 42v25"/><circle class="fill" cx="99" cy="55" r="4"/><circle class="fill" cx="184" cy="92" r="4"/></svg>
<svg class="motion-doodle doodle-pencil" viewBox="0 0 230 110"><path d="m21 76 14-37 133-26 31 22-118 70zM35 39l46 66M168 13l31 22M21 76l60 29"/><path class="dash" d="M65 62 164 37"/></svg>
<svg class="motion-doodle doodle-ship" viewBox="0 0 230 170"><path d="m26 92 84-70 93 71-93 59zM110 22v130M26 92l84 22 93-21"/><path d="m87 78 23-36 24 36-24 18z"/><path class="dash" d="M53 128c36 21 79 26 128 4"/></svg>`;document.body.appendChild(doodles);
const progress=document.createElement('div');progress.className='motion-progress';progress.setAttribute('aria-hidden','true');progress.innerHTML='<span></span><b>00</b>';document.body.appendChild(progress);
const dock=document.createElement('nav');dock.className='motion-top-tools';dock.setAttribute('aria-label','Portfolio experience controls');dock.innerHTML='<button data-action="recruiter">Recruiter · 60 sec</button><button data-action="journey">Play journey</button><button data-action="park">3D park</button><button data-action="assistant">Ask JP-01</button><button data-action="sound">Sound</button><a href="#work">Selected work</a>';document.body.appendChild(dock);
const click=sel=>document.querySelector(sel)?.click();dock.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(a==='recruiter'){if(document.body.classList.contains('studio-locked'))closeIntro();setTimeout(()=>{document.querySelector('#work')?.scrollIntoView({behavior:reduce?'auto':'smooth'});const mode=[...document.querySelectorAll('button,[role="checkbox"],input[type="checkbox"]')].find(el=>/recruiter mode/i.test(el.textContent||el.getAttribute('aria-label')||''));if(mode&&mode.getAttribute('aria-pressed')!=='true'&&mode.getAttribute('aria-checked')!=='true'&&!mode.checked)mode.click()},760)}if(a==='journey')click('.jp-journey-launch');if(a==='park'){sessionStorage.setItem('jp-portfolio-return',location.pathname+location.search+location.hash);click('#jaikar-park-entry')}if(a==='assistant')click('#jp01-launch');if(a==='sound')click('[aria-label*="sound and haptics"]')});
const lockPortfolioTheme=()=>{const toLight=document.querySelector('button[aria-label^="Switch to light mode"]');if(toLight)toLight.click()};lockPortfolioTheme();const themeLockObserver=new MutationObserver(lockPortfolioTheme);themeLockObserver.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['aria-label','class']});
const sections=[...document.querySelectorAll('main section[id],main [id="fieldnotes-feature"]')];sections.forEach(section=>{[...section.children].slice(0,8).forEach((child,i)=>{child.classList.add('motion-reveal');child.style.setProperty('--reveal-order',i)})});
if(!reduce&&'IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('is-visible')}),{threshold:.07,rootMargin:'0px 0px -8%'});document.querySelectorAll('.motion-reveal').forEach(el=>observer.observe(el))}else document.querySelectorAll('.motion-reveal').forEach(el=>el.classList.add('is-visible'));
document.querySelectorAll('header a,header button,.btn-console,.motion-top-tools button,.motion-top-tools a').forEach(el=>{el.addEventListener('pointermove',e=>{if(reduce)return;const r=el.getBoundingClientRect();el.style.setProperty('--mx',`${(e.clientX-r.left-r.width/2)*.09}px`);el.style.setProperty('--my',`${(e.clientY-r.top-r.height/2)*.11}px`)});el.addEventListener('pointerleave',()=>{el.style.setProperty('--mx','0px');el.style.setProperty('--my','0px')})});
document.querySelectorAll('#work img,#showcase img,#fieldnotes-feature img').forEach(img=>{const card=img.closest('button,a')||img;card.classList.add('motion-tilt');card.addEventListener('pointermove',e=>{if(reduce)return;const r=card.getBoundingClientRect();card.style.setProperty('--rx',`${((e.clientY-r.top)/r.height-.5)*-4}deg`);card.style.setProperty('--ry',`${((e.clientX-r.left)/r.width-.5)*5}deg`)});card.addEventListener('pointerleave',()=>{card.style.setProperty('--rx','0deg');card.style.setProperty('--ry','0deg')})});
const update=()=>{const max=document.documentElement.scrollHeight-innerHeight,ratio=max>0?scrollY/max:0;progress.style.setProperty('--read',`${ratio*100}%`);progress.querySelector('b').textContent=String(Math.round(ratio*100)).padStart(2,'0')};update();addEventListener('scroll',update,{passive:true});
})();
